name: Mulberry Bookkeeping
favicon: null
layout_spectrum: 0.6771826243493706
typography_spectrum: 0.5918227834627032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5590745161753148
  lightness: 0.1367319927085191
  saturation: 0.19288216484710574
  rhythmicContrast: 0.5034415875561535
purpose: []
